### ISSUE TITLE
-v Option Not Working

### ISSUE THREAD

**Issue by rudychung** [alexsam29/ssg-cli-tool#2]
The --version option functions as intended, but -v does not work. -v is listed in the list of options in the readme, but does not exist in the help output.

**Comment by rudychung** [comment]
> The --version option functions as intended, but -v does not work. -v is listed in the list of options in the readme, but does not exist in the help output.

**Comment by rudychung** [comment]
The same issue exists with the -h option as well

**Comment by alexsam29** [comment]
Added ```-v``` and ```-h``` as aliases for help and version.  README.MD is now accurate.
